###
GET http://localhost:8881/hello
Accept: text/plain
Cache-Control: no-cache
Content-Type: text/plain

###
GET http://localhost:8881/hello/mono
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

###
GET http://localhost:8881/hello/flux
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

###
GET http://localhost:8881/hello/fluxStream
Accept: */*
Cache-Control: no-cache
Content-Type: application/stream+json

###
